version: "3.9"
services:

  frontend:
    container_name: frontend
    restart: always
    build:
      context: ./harcownik-frontend
      dockerfile: Dockerfile
    volumes:
      - './harcownik-frontend:/app'
      - '/app/node_modules'
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - postgres
    
  postgres:
    container_name: postgres:12
    image: postgres:latest
    volumes: 
      - db:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  db: