version: "3.8"

services:
  # FastAPI web server
  fastapi:
    depends_on: 
      - postgres
    build:
      context: ./harcownik-backend
      dockerfile: Dockerfile
    command: ["bash", "-c", "./pre_test_backend.sh"]
    entrypoint: ["poetry run uvicorn src.main:app --port 8000"]
    ports:
      - "8000:8000"
    environment:
      - postgres_server=postgres
    networks:
      - internal-network

  # PostgreSQL database
  postgres:
    image: postgres:13
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - internal-network

  # PgAdmin web interface
  pgadmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=harcownikapp@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    networks:
      - internal-network

  # React frontend
  frontend:
    build:
      context: ./harcownik-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - internal-network

volumes:
  app-db-data:

networks:
  internal-network: