"""new migration

Revision ID: 74387e70413b
Revises: 54321e8f8ee2
Create Date: 2023-04-24 22:45:30.016825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74387e70413b'
down_revision = '54321e8f8ee2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
