---
name: Generate Python Docstring

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Step 1: Checkout the code repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python and install dependencies
      - name: Set up Python and install dependencies
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"

      - run: pip3 install -r ./.github/generate_docstrings/requirements.txt

      # Step 3: Run the generate docstring script
      - name: Generate Docstrings
        run: /bin/bash ./.github/generate_docstrings/run_generate_docstring.sh ./.github/generate_docstrings/generate_docstrings.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      
      # Step 4: Check if any changes were made
      - name: Check for changes
        id: changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "::set-soutput name=has_changes::true"
          fi

      # Step 5: Commit and push changes to the code repository if any changes were made
      - name: Commit and push changes
        if: steps.changes.outputs.has_changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add docstrings to .py files"
          git push origin HEAD:${{ github.ref }}
