---
name: Continous Integration Pipeline

description: Continous Integration Pipeline for Harcownik

on:
  workflow_dispatch:
  push:
   branches: '*'

  pull_request:
    branches: 'master'

jobs: 
  #run-linter:
  #  uses: ./.github/workflows/test.yaml
  #  with:
  #    test_type: flake8

  #run-pytest:
  #  uses: ./.github/workflows/test.yaml
  #  with:
  #    test_type: py310

  run-jest-tests:
    uses: ./.github/workflows/test_js.yaml

    
