---
name: Continous Integration Pipeline

on:
  workflow_dispatch:
  push:
   branches: '*'

  pull_request:
    branches: 'master'

jobs: 
  install_frontend:
    uses: ./.github/workflows/test_frontend.yaml
