name: Build and push docker images to DockerHub
on:
  workflow_dispatch

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}
      
    - name: Build and tag Docker images
      uses: docker/build-push-action@v2
      with:
        context: ./harcownik-frontend
        push: true
        tags: |
          polo150199/harcownik-frontend:latest
