---
name: Run jest js tests

on:
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install packages
      run: |
        cd harcownik-frontend
        npm install
    
    - name: Run tests
      run: |
        cd harcownik-frontend
        npm test > test_output.txt
      
    - name: Store artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: js-test-output
        retention-days: 14
        path: test_output.txt
