name: Install and test frontend

on:
  workflow_dispatch:
  workflow_call:

jobs:
  frontend_installation:
    runs-on: ubuntu-latest
    steps:
    - name:  Checkout repository
      uses: actions/checkout@v3

    - name: Install packages
      run: |
        cd harcownik-frontend
        npm install

    - name: Start server
      run: |
        cd harcownik-frontend
        npm start
